export default class AppConstants {
  static readonly LOG_DOMAIN: number = 0x0000;
  static readonly LOG_TAG: string = 'ScreenshotPrevention';

  static readonly ERROR_PERMISSION_DENIED: number = 201;

  static readonly FULL_PERCENT: string = '100%';
  static readonly CARD_WIDTH_PERCENT: string = '72%';
  static readonly BUTTON_ROW_WIDTH_PERCENT: string = '72%';
  static readonly MESSAGE_WIDTH_PERCENT: string = '70%';

  static readonly OPACITY_DISABLED: number = 0.35;
}